market_research:
  description: >
    Investigate the latest trends, hashtags, and competitor activities on Twitter specific to the industry of this Twitter account. Focus on gathering data that reveals what content performs well in the current year, identifying patterns, preferences, and emerging trends. 

    Current date: {current_date}

    Description of the Twitter account for which you are doing this research: 
    <TWITTER_ACCOUNT_DESCRIPTION>{twitter_description}</TWITTER_ACCOUNT_DESCRIPTION>

    Find the most relevant topics, hashtags and trends to use in the tweets for next week. The focus of the following week is the following: 
    <NEXT_WEEK_CONTENT>{topic_of_the_week}</NEXT_WEEK_CONTENT>

  expected_output: >
    A report with the most relevant information that you found, including relevant hashtags for this week's content and all other information that could be useful to the team working on content creation.

content_strategy:
  description: >
    Based on the market research findings, develop a comprehensive content calendar for a week. The calendar should specify the theme for each day of the week (from Monday to Sunday) where some content should be posted, and preliminary ideas for tweet content. For now, focus on a three-day content calendar, including the most relevant keywords and hashtags to use in each tweet.
  expected_output: >
    A detailed week-long content calendar, formatted as markdown, that includes days of the week (from Monday to Friday), a brief overview of content ideas, and the most relevant keywords and hashtags to use in each tweet. Ensure the calendar aligns with the identified trends and audience preferences.

visual_content_creation:
  description: >
    Adapt or create visual content suitable for tweets based on the content strategy for each Twitter post. To do that, you will need to create a detailed description of the image that you will use for each day. Describe the colors, the objects, the mood, and any other relevant information that you think is important for the image to be created, while ensuring it complements the tweet's text and fits within Twitter's image guidelines.

  expected_output: >
    A markdown document with detailed descriptions of the images that will be used for each Twitter post of the week. Each description should be concise and include the main elements, colors, mood, and any other relevant information that will guide the creation of the image. The descriptions should align with the content calendar and the identified trends.

copywriting:
  description: >
    Write captivating and relevant tweet copy for each Twitter post of the week, aligning to the strategic themes of the content calendar. The copy should engage the audience, embody the brand's voice, and encourage interaction. The copy should also be concise to fit Twitter's character limits and incorporate the relevant keywords and hashtags contained in the content schedule. 

  expected_output: >
    A document formatted as markdown, with several sections. Each section should contain the copy for a single Twitter post, along with the relevant hashtags and calls to action. The copy should be engaging, on-brand, and aligned with the content calendar.

report_final_content_strategy:
  description: >
    Compile a comprehensive report that outlines the final content strategy for the week. The report should include the market research findings, the content calendar, the tweet copy for each post, and the AI-generated images. Provide a brief rationale for the strategy, explaining how it aligns with the identified trends and audience preferences.

  expected_output: >
    A detailed report that includes the market research findings, the content calendar, the tweet copy for each post, and the AI-generated images. The report should be formatted as markdown and include a brief rationale for the strategy, explaining how it aligns with the identified trends and audience preferences.